#!/usr/bin/env python3
"""
Nightly Batch Generator Template
- Copy this file and modify for your specific batch job
- Requires: /tmp/hermes-run-venv (see slow-local-model-batch skill)
"""

import sys
from pathlib import Path
from datetime import datetime

# ─── CONFIG ───
HERMES_AGENT = Path("/mnt/c/Users/User/hermes-agent")
sys.path.insert(0, str(HERMES_AGENT))

OUTPUT_DIR = Path.home() / ".hermes" / "narratives" / "news"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Check deps
try:
    from dotenv import load_dotenv
except ImportError:
    print("ERROR: python-dotenv not found. Run with /tmp/hermes-run-venv/bin/python")
    sys.exit(1)

from run_agent import AIAgent

# ─── YOUR PROMPTS ───
PROMPTS = {
    "Style1": """YOUR PROMPT HERE...

Content to process:
{content}

Generate output:""",
    
    "Style2": """YOUR PROMPT HERE...

Content to process:
{content}

Generate output:""",
}

# ─── MOCK DATA (replace with real fetch) ───
MOCK_CONTENT = """Your mock or fetched content here..."""

# ─── FUNCTIONS ───

def generate_with_agent(prompt, provider="ollama-local", model="gemma4:e4b"):
    """Generate content using slow local model."""
    agent = AIAgent(
        provider=provider,
        model=model,
        max_iterations=2,      # Limit to prevent runaway
        quiet_mode=True,
    )
    return agent.chat(prompt)

def clean_output(text):
    """Remove meta-text and stage directions."""
    import re
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'\(.*?\)', '', text)
    text = re.sub(r'#{1,6}\s*คำแนะนำ.*?(?=---|$)', '', text, flags=re.DOTALL)
    text = re.sub(r'\*\*💡.*?(?=---|$)', '', text, flags=re.DOTALL)
    text = re.sub(r'\[SCRIPT\]\s*', '', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

def save_output(content, style_name, date_str):
    """Save to markdown file."""
    filename = f"{date_str}_{style_name.replace(' ', '_')}.md"
    filepath = OUTPUT_DIR / filename
    
    md = f"""# {style_name} — {date_str}

> Generated by {model} via {provider} at {datetime.now().strftime('%H:%M:%S')}

---

{content}

---
*Generated automatically*
"""
    filepath.write_text(md, encoding='utf-8')
    return filepath

def main():
    date_str = datetime.now().strftime('%Y-%m-%d')
    print(f"=== Batch Generator ({date_str}) ===")
    
    for style, template in PROMPTS.items():
        print(f"\nGenerating {style}...")
        prompt = template.format(content=MOCK_CONTENT)
        raw = generate_with_agent(prompt)
        clean = clean_output(raw)
        filepath = save_output(clean, style, date_str)
        print(f"Saved: {filepath} ({len(clean)} chars)")
    
    print("\n=== DONE ===")

if __name__ == "__main__":
    main()
